### ISSUE TITLE
Meeco Integration - VP4OIDC Authentication

### ISSUE THREAD

**Issue by hnamzian** [hashgraph/guardian#2261]
### Problem description
Guardian already supports a username/password authentication that users must (potentially) provide their identity information and a password by forms. Alternatively, it is very common to use passwordless methods for authentication in decentralized manner that brings several benefits to users, like more smoothly register/login, not being required to remember passwords. more secure authentication while managing their identity by themselves and providing selective field exposure.
Meeco is a decentralized identity management solution under hashgrapgh umbrella which is potentially an ideal solution to integrate with Guradian, providing vc4oidc authentication.

### Requirements
Meeco integration would be an alternative to current authentication method, not a replacement and can be selected in configuration of auth-service to use either or both auth methods.
https://meeco.me

### Definition of done
Having selected Meeco as Authentication method in auth-service configs, the user who has been registered in Meeco will be able to register/login to Guardian application by using Meeco Wallet, presenting VP and being verified by Guardian.
The VP schema must be defined in the Guardian configurations and created to Meeco in order to request the fields mentioned in the schema from user.
Only VPs issued by a whitelisted entity will be approved. The whitelisted issuers must be stored in the database.

### Acceptance criteria
As a user registered to Meeco platform, I would be able to use Meeco Wallet to present Verifiable Presentation of my credential/identity. The process will be started by requesting a new login and proceeded by scanning the QR code shown by Guardian identity page by my Meeco Wallet in order to send my VP and will be concluded by VP being verified by meeco.
```[tasklist]
### Tasks
- [x] Create Websocket APIs for meeco Authentication
- [x] Develop Meeco API interface
- [x] Develop Cryppo helper class
- [x] Integrate Auth Service with Meeco
- [x] Connect Auth Service and API Gateway for Meeco Integration
- [ ] Meeco Integration Document
- [ ] Meeco Auth Frontend
```
